spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patient_info?useSSL=false
    username: root
    password: tDosprg$22

#JPA Settings
  jpa.hibernate.ddl_auto: update

  springdoc:
    swagger-ui:
      enabled=true: